import { Check, ChevronRight, CircleAlert, Download, FileSpreadsheet, Filter, Image, Plus, Printer, Search, Settings2, Upload, Users, X } from 'lucide-react'
import { dashboardData } from '../data/mockData'
import { StatusBadge } from '../components/StatusBadge'

const materials = [
  ['MAT-00023', '蔗糖', 'Sucrose', 'A1', '12 张'],
  ['MAT-00024', '维生素 D3', 'Vitamin D3', 'E2', '6 张'],
  ['MAT-00025', '草莓香精', 'Strawberry Flavor', 'F-02', '9 张'],
  ['MAT-00026', '乳酸菌粉', 'Lactic Acid Bacteria', 'B7', '4 张'],
]
const recipes = [
  ['高钙纯牛奶 1L', '4 种辅料', '2026-09-08 16:20', '启用'],
  ['草莓风味酸牛奶', '6 种辅料', '2026-09-08 15:04', '启用'],
  ['原味风味发酵乳', '5 种辅料', '2026-09-07 11:42', '启用'],
]

export function WorkOrdersPage({ approvals = false }: { approvals?: boolean }) {
  return <div className="page-wrap"><PageTitle eyebrow={approvals ? 'REVIEW QUEUE' : 'PRODUCTION ORDERS'} title={approvals ? '审批中心' : '工单管理'} sub={approvals ? '处理需要管理员确认的现场申请，审批结果会立即同步到平板。' : '集中查看生产工单、执行进度和辅料称量证据。'} action={approvals ? undefined : <button className="primary-button"><Plus size={16} />新建工单</button>} /><div className="page-toolbar"><div className="search-box"><Search size={16} /><input placeholder="搜索工单号、产品或操作员" /></div><button className="filter-button"><Filter size={14} />全部状态 <ChevronRight size={14} /></button><button className="outline-button"><Download size={15} />导出</button></div>{approvals ? <ApprovalTable /> : <div className="panel full-panel"><div className="table-wrap"><table><thead><tr><th>工单信息</th><th>目标产量</th><th>进度</th><th>操作员</th><th>状态</th><th>更新时间</th><th /></tr></thead><tbody>{dashboardData.workOrders.concat(dashboardData.workOrders.slice(1, 3)).map((order, index) => <tr key={`${order.id}-${index}`}><td><strong className="order-id">{order.id}</strong><span className="order-product">{order.product}<small>{order.batch}</small></span></td><td>{order.targetWeight.toLocaleString()} kg</td><td><div className="progress-row"><div className="progress"><i style={{ width: `${(order.completedSteps / order.totalSteps) * 100}%` }} /></div><span>{order.completedSteps}/{order.totalSteps}</span></div></td><td><span className="operator"><span className="operator-dot">{order.operator.slice(0, 1)}</span>{order.operator}</span></td><td><StatusBadge status={order.status} /></td><td className="muted">今天 {order.updatedAt}</td><td><button className="icon-btn"><ChevronRight size={17} /></button></td></tr>)}</tbody></table></div></div>}</div>
}

function ApprovalTable() { return <div className="approval-grid">{dashboardData.pendingApprovals.concat([{ id: 'AP-015', title: '称重证据复核', description: 'WO-20260908-010 · 乳酸菌粉', time: '1小时前', type: 'photo' as const }]).map((item) => <div className="approval-card" key={item.id}><div className={`approval-icon ${item.type}`}><CircleAlert size={18} /></div><div className="approval-copy"><small>{item.id} · {item.time}</small><strong>{item.title}</strong><span>{item.description}</span></div><div className="approval-actions"><button className="reject-button"><X size={15} />驳回</button><button className="approve-button wide"><Check size={15} />批准</button></div></div>)}</div> }

export function MaterialsPage({ recipesPage = false }: { recipesPage?: boolean }) { return <div className="page-wrap"><PageTitle eyebrow="MASTER DATA" title={recipesPage ? '产品与配方' : '辅料管理'} sub={recipesPage ? '维护产品配方，按每吨成品配置辅料用量。' : '维护辅料代号、名称和用于现场识别的包装图片。'} action={<button className="primary-button"><Plus size={16} />新增{recipesPage ? '产品' : '辅料'}</button>} /><div className="page-toolbar"><div className="search-box"><Search size={16} /><input placeholder={`搜索${recipesPage ? '产品名称' : '辅料代号、名称'}`} /></div><button className="outline-button"><FileSpreadsheet size={15} />Excel 导入</button><button className="outline-button"><Download size={15} />导出模板</button></div>{recipesPage ? <div className="recipe-grid">{recipes.map((recipe) => <div className="recipe-card" key={recipe[0]}><div className="recipe-head"><span className="recipe-icon"><FileSpreadsheet size={18} /></span><span className="enabled-dot" /><button className="icon-btn"><ChevronRight size={17} /></button></div><h3>{recipe[0]}</h3><p>{recipe[1]} · 最近更新 {recipe[2]}</p><div className="recipe-foot"><span>配方状态</span><b>{recipe[3]}</b><ChevronRight size={14} /></div></div>)}</div> : <div className="panel full-panel"><div className="table-wrap"><table><thead><tr><th>辅料 ID / 代号</th><th>中文名称</th><th>英文名称</th><th>包装图片</th><th>状态</th><th /></tr></thead><tbody>{materials.map((material) => <tr key={material[0]}><td><strong className="order-id">{material[0]}</strong><span className="code-pill">{material[3]}</span></td><td><strong className="table-primary">{material[1]}</strong></td><td className="muted">{material[2]}</td><td><span className="image-count"><Image size={14} />{material[4]}</span></td><td><span className="status status-running"><i />启用</span></td><td><button className="icon-btn"><ChevronRight size={17} /></button></td></tr>)}</tbody></table></div></div>}</div> }

export function LabelsPage() { return <div className="page-wrap"><PageTitle eyebrow="LABEL OPERATIONS" title="标签打印" sub="生成并打印公司自制二维码标签，打印完成后请粘贴到对应辅料包装。" /><div className="label-layout"><section className="panel form-panel"><div className="panel-head"><div><h2>生成标签</h2><p>每张标签拥有独立编号，打印时间自动记录</p></div><Printer size={20} className="panel-head-icon" /></div><label>选择辅料<select><option>请选择需要打印的辅料</option><option>蔗糖 · A1</option><option>维生素 D3 · E2</option><option>草莓香精 · F-02</option></select></label><label>打印张数<div className="stepper"><button>−</button><strong>10</strong><button>＋</button></div></label><div className="info-note"><CircleAlert size={16} /><span>打印日期将自动使用当前系统时间，第一版不录入实际生产日期。</span></div><button className="primary-button print-button"><Printer size={16} />生成并打印标签</button></section><section className="panel preview-panel"><div className="panel-head"><div><h2>标签预览</h2><p>打印前确认标签信息</p></div><span className="preview-tag">预览</span></div><div className="label-preview"><div className="label-top"><strong>牧衡 · 辅料标签</strong><span>ACTIVE</span></div><div className="fake-qr">▦</div><strong className="preview-material">等待选择辅料</strong><span className="preview-code">内部代号 —　·　打印日期 2026-09-09</span><small>扫描此二维码确认辅料身份</small></div></section></div><div className="section-label"><span>最近打印批次</span><i /></div><div className="panel full-panel"><div className="table-wrap"><table><thead><tr><th>打印批次</th><th>辅料</th><th>张数</th><th>打印人</th><th>时间</th><th>状态</th></tr></thead><tbody><tr><td className="order-id">PB-20260909-004</td><td>蔗糖 · A1</td><td>20 张</td><td>系统管理员</td><td>今天 09:40</td><td><span className="status status-running"><i />已确认</span></td></tr><tr><td className="order-id">PB-20260908-003</td><td>维生素 D3 · E2</td><td>10 张</td><td>系统管理员</td><td>昨天 16:15</td><td><span className="status status-takeover"><i />待复核</span></td></tr></tbody></table></div></div></div> }

export function SettingsPage({ accounts = false }: { accounts?: boolean }) { return <div className="page-wrap"><PageTitle eyebrow="SYSTEM CONFIGURATION" title={accounts ? '账号管理' : '系统设置'} sub={accounts ? '创建和管理普通操作员账号，管理员权限由系统预置。' : '维护称重允差、系统备份和现场设备连接参数。'} action={accounts ? <button className="primary-button"><Plus size={16} />新建账号</button> : undefined} />{accounts ? <div className="panel full-panel"><div className="table-wrap"><table><thead><tr><th>账号</th><th>姓名</th><th>角色</th><th>最近登录</th><th>状态</th><th /></tr></thead><tbody>{[['operator01','李师傅','普通操作员','今天 08:01'],['operator02','王师傅','普通操作员','今天 07:56'],['operator03','赵师傅','普通操作员','昨天 17:44']].map((user) => <tr key={user[0]}><td className="order-id">{user[0]}</td><td><span className="operator"><span className="operator-dot">{user[1].slice(0, 1)}</span>{user[1]}</span></td><td>{user[2]}</td><td className="muted">{user[3]}</td><td><span className="status status-running"><i />正常</span></td><td><button className="icon-btn"><Settings2 size={16} /></button></td></tr>)}</tbody></table></div></div> : <div className="settings-grid"><Setting title="默认称重允差" description="目标重量的相对比例" value="1.0 %"/><Setting title="最小绝对允差" description="低于此重量时使用的下限" value="5 g"/><Setting title="自动备份" description="数据库和证据文件的本地备份" value="每天 02:00"/><Setting title="服务端口" description="局域网访问端口" value="8000"/></div>}</div> }
function Setting({ title, description, value }: { title: string; description: string; value: string }) { return <div className="setting-row"><div className="setting-icon"><Settings2 size={17} /></div><div><strong>{title}</strong><span>{description}</span></div><button className="setting-value">{value}<ChevronRight size={15} /></button></div> }
function PageTitle({ eyebrow, title, sub, action }: { eyebrow: string; title: string; sub: string; action?: React.ReactNode }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="heading-sub">{sub}</p></div>{action}</section> }
